# Generated by Django 5.2.3 on 2026-03-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_duration_seconds_match_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='discord_channel_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Discord Channel ID'),
        ),
        migrations.AddField(
            model_name='match',
            name='discord_guild_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Discord Guild ID'),
        ),
        migrations.AddField(
            model_name='match',
            name='discord_message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Discord Message ID'),
        ),
        migrations.AddField(
            model_name='match',
            name='external_match_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='External match key'),
        ),
        migrations.AddField(
            model_name='match',
            name='win_message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Win Message ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=16, verbose_name='Статус матча'),
        ),
    ]
