# Generated by Django 5.2.3 on 2026-03-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_discord_channel_id_match_discord_guild_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('ready', 'Ready'), ('started', 'Started'), ('win_set', 'Win Set'), ('canceled', 'Canceled'), ('status_changed', 'Status Changed')], max_length=64),
        ),
    ]
